apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-helm-m1.fullname" . }}
  labels:
    {{- include "flask-helm-m1.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-helm-m1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-helm-m1.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "flask-helm-m1.serviceAccountName" . }}
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          # The following env entries reference an EXTERNAL Secret named "<fullname>-secrets".
          # Only keys listed in .Values.secretEnvKeys will be requested.
          env:
            {{- $secretName := include "flask-helm-m1.secretName" . -}}
            {{- range .Values.secretEnvKeys }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .name }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
