# /Mid-Level/GHA-M-1/solution.yml
# GHA-M-1: CI/CD with Docker Push & Helm Deploy Trigger (simulation only)
# Verification:
# - Trigger: on merge to 'main' branch
# - Build: Dockerfile from /Mid-Level/GHA-M-1/prerequisites
# - Push: to Google Artifact Registry (GAR) with SHA tag
# - Simulate: print helm upgrade command with image repo + SHA

name: GHA-M-1 --- CI/CD with Docker Push + Helm Deploy Trigger

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "Mid-Level/GHA-M-1/**"
      - ".github/workflows/gha-m-1.yml"

permissions:
  contents: read
  id-token: write

jobs:
  build-push-simulate-helm:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "stable-healer-418019"
      GAR_REGION: "europe-west3"
      GAR_REPO: "apps"
      IMAGE_NAME: "gha-m-1-app"
      DOCKERFILE_DIR: "Mid-Level/GHA-M-1/prerequisites"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Ensure GAR repository exists 
        run: |
          if ! gcloud artifacts repositories describe "$GAR_REPO" --location="$GAR_REGION" >/dev/null 2>&1; then
            gcloud artifacts repositories create "$GAR_REPO" \
              --repository-format=docker \
              --location="$GAR_REGION" \
              --description="Docker images for mid-level tasks"
          else
            echo "Repository $GAR_REPO already exists in $GAR_REGION"
          fi

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker $GAR_REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t "$GAR_REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:sha-${GITHUB_SHA::8}" "$DOCKERFILE_DIR"

      - name: Push Docker image to GAR
        run: docker push "$GAR_REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:sha-${GITHUB_SHA::8}"

      - name: Simulate Helm deploy (echo only)
        run: |
          echo "helm upgrade --install gha-m-1 bitnami/nginx \
            --set image.registry='$GAR_REGION-docker.pkg.dev' \
            --set image.repository='$PROJECT_ID/$GAR_REPO/$IMAGE_NAME' \
            --set image.tag='sha-${GITHUB_SHA::8}' \
            --namespace default"

      - name: Summary
        run: |
          echo "Built and pushed: $GAR_REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE_NAME:sha-${GITHUB_SHA::8}"
          echo "Simulated Helm command printed above (bitnami/nginx). No deployment performed."
